from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

import os

styles = getSampleStyleSheet()


def create_pdf():

    print("\nPDF raporu hazırlanıyor...")

    pdf = SimpleDocTemplate(
        "Smart_Log_Analyzer_Report.pdf"
    )

    story = []

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    story.append(
        Paragraph(
            "SMART LOG ANALYZER REPORT",
            title
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "Automatic Log Analysis Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "This report was automatically generated by the Smart Log Analyzer project.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,25))

    # -----------------------
    # KMeans
    # -----------------------

    if os.path.exists("kmeans_graph.png"):

        story.append(
            Paragraph(
                "<b>K-Means Clustering</b>",
                styles["Heading2"]
            )
        )

        story.append(
            Image(
                "kmeans_graph.png",
                width=420,
                height=320
            )
        )

        story.append(Spacer(1,20))

    # -----------------------
    # DBSCAN
    # -----------------------

    if os.path.exists("dbscan_graph.png"):

        story.append(
            Paragraph(
                "<b>DBSCAN Clustering</b>",
                styles["Heading2"]
            )
        )

        story.append(
            Image(
                "dbscan_graph.png",
                width=420,
                height=320
            )
        )

        story.append(Spacer(1,20))

    # -----------------------
    # Elbow
    # -----------------------

    if os.path.exists("elbow_method.png"):

        story.append(
            Paragraph(
                "<b>Elbow Method</b>",
                styles["Heading2"]
            )
        )

        story.append(
            Image(
                "elbow_method.png",
                width=420,
                height=320
            )
        )

    pdf.build(story)

    print("Smart_Log_Analyzer_Report.pdf oluşturuldu.")


if __name__ == "__main__":
    create_pdf()